### ISSUE TITLE
Async support?

### ISSUE THREAD

**Issue by sliterok** [izure1/serializable-bptree#1] opened 2024-03-09 10:39 UTC
Hey, I wanted to make a DB for [OPFS](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Origin_private_file_system) and I thought that your bp-tree lib is an ideal candidate with one exception. It's fully synchronous. But other libs were much harder to work on so I decided that I could just add async to your lib.
I've made a demo with my DB here https://sliterok.github.io/opfs-demo/ and source is [here](https://github.com/sliterok/opfs-demo).

After I made it I checked your github profile and it appears that you've also made a DB with this bptree, so I wasn't sure if you would be interested in the PR that adds asyncs.
In future I wanted to do some benchmarks to see if my solution is feasible on large scale, but I feel like at this point I verified that most of it works as expected.
If benchmarks go good might as well publish on npm, because as of right now you can use only sqlite in OPFS and it has some limitations.

**Comment by izure1** [comment] 2024-03-10 05:45
Hello, thank you for providing the demo and the source. I have checked both and am also thinking positively about adding asynchronous operations. I appreciate your dedication to solving this issue.

However, I am a bit concerned about the potential concurrency issues with asynchronous read/write operations. This is because the current library minimizes file input/output by performing reads from an in-memory cache after the initial access, except for the first time.

Moreover, asynchronous operations could potentially have a negative impact on performance compared to synchronous tasks. Therefore, if implemented, it would be provided as a separate class.

I would like to approach these issues cautiously, so it seems that some time will be needed.

**Comment by izure1** [comment] 2024-03-11 19:29
The 3.0.0 update, which includes support for asynchronous operations, has been released. You can now download and use it from npm. If there are any additional features related to asynchronous support that you need, please leave a comment. 🙏

**Comment by sliterok** [comment] 2024-03-11 19:54
I love it! Thank you for your work, I really appreciate that. There's one thing that I noticed when testing with a lot of data. It takes a long time to go through a big tree. For in-browser use I would guess that you would want to slice that data. I've implemented limit here https://github.com/sliterok/opfs-demo/commit/dee2392225b1d26da1819c9fb3a3c9acfc2bf856 and it greatly reduced the search time. Probably pagination would be a next best thing to implement.

**Comment by izure1** [comment] 2024-03-11 20:34
Thank you. I've reviewed the source code. It seems to be an issue with the **like** and **notEqual** operators. These operators require scanning all nodes rather than leveraging the indexing advantages of B+trees.

Therefore, I considered pagination as a good alternative. However, I realized a problem when implementing it with multiple conditions. If there are multiple conditions, and we treat each search result as a set, the intersection count may be much less than desired.

For example, if we search for 50 items under condition A and 50 items under condition B, and then perform an AND operation, the result may be less than 50 items. This doesn't seem like a good user experience for developers.

Considering all these points, I believe further consideration is needed. 🙂

**Comment by izure1** [comment] 2024-03-11 22:56
I have conducted further performance testing on this matter.

In a state where there are 10k user records, the `OPFSDB.query` method's `tree.keys` method showed an average delay of about `5ms` without page limitations. (Upon initial connection, it increased up to `1500ms` due to caching.)

Most of the performance issues occurred in the `readMany` function, which increased proportionally to the number of retrieved data.
It seems like these issues stem from the file I/O process in the `readFile` function.
Is there a way to optimize this function? Currently, it doesn't seem like a problem with the library itself.

**Comment by sliterok** [comment] 2024-03-12 07:51
I've tried to investigate other OPFS API options and it appears that there are 3 ways of using it:
1) get File constructor and convert it to arrayBuffer (currently used)
2) get readable and pipe it like a stream to arrayBuffer and use it (should be in repo history)
3) construct arrayBuffer and pass it to the "read" method https://developer.mozilla.org/en-US/docs/Web/API/FileSystemSyncAccessHandle/read

I've tried first two and they're not much different, I haven't yet tried the third one because it appears that it only works with webworkers and I've been using service worker to avoid any issues with concurrency (also to be able to intercept fetch requests because it seems like the simplest way to create an api)
I have feeling that the last way should add some performance, I will try to investigate that.
But in any way, when there are like 20mb of data in the collection (I checked through "app" tab in debugger) it starts to slow down the search and "limit" feels like the only thing that can help fundamentally.
Comparing to how much it takes to load the "data" itself getting indexes feels pretty fast, so I would think that it isn't about optimization but maybe the browser itself? Some i/o speed limitation of sorts, because both of my drive on this system are nvme.

**Comment by sliterok** [comment] 2024-03-12 19:22
I've changed the code to work as a web worker and adapted the 3rd API. Looks like now it's much faster. Also I increased the order because it yields to both faster inserts and reads. Although when I was testing same API for writes I got worse results than createWritable.

**Comment by izure1** [comment] 2024-03-13 10:13
The reason for slow write operations is that when the tree is updated, related nodes are collectively updated to balance the tree nodes. During this process, the same node may be updated multiple times. Therefore, leveraging delayed writing functionality for each node may provide performance benefits.

Please refer to the following details:
https://github.com/izure1/serializable-bptree?tab=readme-ov-file#writeid-number-node-bptreenodek-v-void

I believe the [p-debounce](https://www.npmjs.com/package/p-debounce) library could be helpful for you.

**Comment by sliterok** [comment] 2024-03-13 12:31
Indeed, delayed writes improved the performance 2-3x but it feels a bit inconsistent in terms of how much time the import takes. It ranges from 1500ms to 4500ms. I think it's acceptable but probably there's a better way of handling writes like these?

**Comment by sliterok** [comment] 2024-03-13 13:57
I was thinking about doing that with the record itself, but it makes sense that index storage could also be optimized this way. I will give it a try.

**Comment by sliterok** [comment] 2024-03-14 09:03
I'm testing both fixed-length tree storage and dynamic-length one file buffer for record storage and I'm having issues when I'm trying to "import" users
![image](https://github.com/izure1/serializable-bptree/assets/12751644/b370e780-bd72-4f5d-b69b-5e59f6b2c02a)
RecordsIndex is a btree that holds start and end of the record as a key and id as a value. And for some reason id = 2 isn't complying with the "order" which is set to 15 while pageSize is already at 65536 which is probably quite large.
Other ids have lower values, but I'm pretty sure they're bigger than they should be...
I have feeling it may be because of collisions in id generation, I need it sequential to be able to store pages and I'm not completely sure I implemented it consistent. But I feel like it wouldn't decode properly if it was colliding.
I've updated the btpree to your version just in case it's something with async but I still get same behavior.

**Comment by izure1** [comment] 2024-03-14 12:35
I've attempted to reproduce the issue, but I couldn't encounter the same behavior.
Could you please provide the source code for me to reproduce this issue?

**Comment by izure1** [comment] 2024-03-14 14:57
It seems like the issue arises from not waiting for asynchronous operations during data insertion and retrieval.

Instead of using the map function, try using a for loop. I've made the following modifications to the code at the specified link, and I've confirmed that it works properly.

https://github.com/sliterok/opfs-demo/blob/bc907bb6d48b887b2d382502d9ccf4740430e08d/src/db/index.ts#L347

```
for (const record of records) {
  const encoded = this.encoder.encode(record.value)
  const at = this.lastIndex
  const to = at + encoded.length
  this.lastIndex = to
  
  await this.recordsIndex.insert(`${at},${to}`, record.id)
  await writeFile(this.recordsRoot, 'records', encoded, false, at, to)
}
for (const key of Object.keys(this.trees)) {
  const tree = this.trees[key]
  for (const record of records) {
    const val = record.value[key]
    if (val === undefined || val === null) continue
    await tree.insert(record.id, val)
  }
}
```

**Comment by sliterok** [comment] 2024-03-14 15:20
I guess I don't need to do parallel executions if it writes synchronously. Thank you for help.
I've used the code you provided and the results are surprisingly close to this paid plugin for rxdb https://rxdb.info/rx-storage-opfs.html
Probably making this into a library is a good idea after all.
One thing that I also noticed that for index I had to call writeHead from the FileStoreStrategy and it's not very convenient to add the index counter to the read and write methods.
I think it makes sense to add head data to the "id" function and allow to extend it on new node creation.

**Comment by sliterok** [comment] 2024-03-14 15:39
Also another issue popped up when enough users were added, the keys list will grow without being limited by the order, which in turn makes the nodes not being fixed-size.
![image](https://github.com/izure1/serializable-bptree/assets/12751644/0e948e27-3307-4c5c-8628-9909926e8aea)

**Comment by izure1** [comment] 2024-03-14 16:05
Thank you for the feedback. I'll consider adding a feature to easily modify the head data in the id method.
Also, I've noticed that there's a missing await in one place. That might be the issue.

https://github.com/sliterok/opfs-demo/blob/58ed419ee5ee0ace6cdfbdf35aadb9d6aa7f8db6/src/db/index.ts#L375

**Comment by sliterok** [comment] 2024-03-14 16:09
I will fix it, thank you. Although I was mostly testing with the import code you sent, so this shouldn't affect it much.

**Comment by izure1** [comment] 2024-03-20 20:28
I will consider this issue resolved and proceed to close it. Please let me know if there are any new issues. :)

**Closed by izure1** 2024-03-20 20:28 UTC
Labels: enhancement
